In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data = '/content/drive/My Drive/Colab Notebooks/mlb_batters_final.csv'

In [ ]:
import pandas as pd
df = pd.read_csv(data,low_memory=False)

In [ ]:
import numpy as np

In [ ]:
df = df.dropna(axis=1) #비어있는 열 삭제

In [ ]:
df

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,WAR,Spd,BsR,Def,wSB,Age Rng,Off,Lg,Events,L-WAR
0,10,2001,David Eckstein,ANA,26,153,582,664,166,134,...,2.2,6.0,4.0,0.1,4.0,26 - 26,-0.5,2.3,0,2.2
1,10,2002,David Eckstein,ANA,27,152,608,702,178,142,...,4.5,6.2,5.7,10.6,-1.3,27 - 27,10.2,2.4,0,4.5
2,10,2003,David Eckstein,ANA,28,120,452,517,114,88,...,1.2,5.2,0.3,7.8,1.0,28 - 28,-13.9,1.9,0,1.2
3,10,2004,David Eckstein,ANA,29,142,566,637,156,129,...,1.9,5.1,2.9,9.3,0.9,29 - 29,-11.1,2.0,0,1.9
4,10,2005,David Eckstein,STL,30,158,630,713,185,144,...,2.5,4.8,-1.7,-1.6,-1.5,30 - 30,3.2,1.5,0,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24775,9957(2),2015,Steve Pearce,BAL,32,92,294,325,64,35,...,0.1,3.4,-0.3,-6.4,-0.3,32 - 32,-3.1,1.1,226,0.1
24776,9957(2),2016,Steve Pearce,- - -,33,85,264,302,76,49,...,1.8,2.2,0.0,-6.3,-1.4,33 - 33,13.1,1.2,211,2.1
24777,9957(2),2017,Steve Pearce,TOR,34,92,313,348,79,48,...,0.0,1.9,-1.0,-11.0,-0.2,34 - 34,-0.9,0.9,248,0.1
24778,9957(2),2018,Steve Pearce,- - -,35,76,215,251,61,35,...,1.7,2.4,1.2,-5.6,-0.2,35 - 35,13.3,1.0,176,1.6
24779,9957(2),2019,Steve Pearce,BOS,36,29,89,99,16,11,...,-0.8,1.8,-0.8,-2.2,0.0,36 - 36,-9.9,0.5,60,-0.9

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24780 entries, 0 to 24779
Data columns (total 50 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   IDfg     24780 non-null  object
 1   Season   24780 non-null  int64
 2   Name     24780 non-null  object
 3   Team     24780 non-null  object
 4   Age      24780 non-null  int64
 5   G        24780 non-null  int64
 6   AB       24780 non-null  int64
 7   PA       24780 non-null  int64
 8   H        24780 non-null  int64
 9   1B       24780 non-null  int64
 10  2B       24780 non-null  int64
 11  3B       24780 non-null  int64
 12  HR       24780 non-null  int64
 13  R        24780 non-null  int64
 14  RBI      24780 non-null  float64
 15  BB       24780 non-null  int64
 16  IBB      24780 non-null  float64
 17  SO       24780 non-null  float64
 18  HBP      24780 non-null  float64
 19  SF       24780 non-null  float64
 20  SH       24780 non-null  float64
 21  GDP      24780 non-null  float64
 22  SB       24780 non-null  float64
 23  CS       24780 non-null  float64
 24  AVG      24780 non-null  float64
 25  BB%      24780 non-null  float64
 26  K%       24780 non-null  float64
 27  BB/K     24780 non-null  float64
 28  OBP      24780 non-null  float64
 29  SLG      24780 non-null  float64
 30  OPS      24780 non-null  float64
 31  ISO      24780 non-null  float64
 32  BABIP    24780 non-null  float64
 33  wOBA     24780 non-null  float64
 34  wRAA     24780 non-null  float64
 35  wRC      24780 non-null  int64
 36  Bat      24780 non-null  float64
 37  Rep      24780 non-null  float64
 38  Pos      24780 non-null  float64
 39  RAR      24780 non-null  float64
 40  WAR      24780 non-null  float64
 41  Spd      24780 non-null  float64
 42  BsR      24780 non-null  float64
 43  Def      24780 non-null  float64
 44  wSB      24780 non-null  float64
 45  Age Rng  24780 non-null  object
 46  Off      24780 non-null  float64
 47  Lg       24780 non-null  float64
 48  Events   24780 non-null  int64
 49  L-WAR    24780 non-null  float64
dtypes: float64(32), int64(14), object(4)
memory usage: 9.5+ MB

#(1) Basic Data Preprocessing
HR, R 보정 및 무의미한 열 삭제

In [ ]:
df['HR'] = df['HR'] / df['AB']

In [ ]:
df['R'] = df['R'] / df['PA']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24780 entries, 0 to 24779
Data columns (total 50 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   IDfg     24780 non-null  object
 1   Season   24780 non-null  int64
 2   Name     24780 non-null  object
 3   Team     24780 non-null  object
 4   Age      24780 non-null  int64
 5   G        24780 non-null  int64
 6   AB       24780 non-null  int64
 7   PA       24780 non-null  int64
 8   H        24780 non-null  int64
 9   1B       24780 non-null  int64
 10  2B       24780 non-null  int64
 11  3B       24780 non-null  int64
 12  HR       22873 non-null  float64
 13  R        22925 non-null  float64
 14  RBI      24780 non-null  float64
 15  BB       24780 non-null  int64
 16  IBB      24780 non-null  float64
 17  SO       24780 non-null  float64
 18  HBP      24780 non-null  float64
 19  SF       24780 non-null  float64
 20  SH       24780 non-null  float64
 21  GDP      24780 non-null  float64
 22  SB       24780 non-null  float64
 23  CS       24780 non-null  float64
 24  AVG      24780 non-null  float64
 25  BB%      24780 non-null  float64
 26  K%       24780 non-null  float64
 27  BB/K     24780 non-null  float64
 28  OBP      24780 non-null  float64
 29  SLG      24780 non-null  float64
 30  OPS      24780 non-null  float64
 31  ISO      24780 non-null  float64
 32  BABIP    24780 non-null  float64
 33  wOBA     24780 non-null  float64
 34  wRAA     24780 non-null  float64
 35  wRC      24780 non-null  int64
 36  Bat      24780 non-null  float64
 37  Rep      24780 non-null  float64
 38  Pos      24780 non-null  float64
 39  RAR      24780 non-null  float64
 40  WAR      24780 non-null  float64
 41  Spd      24780 non-null  float64
 42  BsR      24780 non-null  float64
 43  Def      24780 non-null  float64
 44  wSB      24780 non-null  float64
 45  Age Rng  24780 non-null  object
 46  Off      24780 non-null  float64
 47  Lg       24780 non-null  float64
 48  Events   24780 non-null  int64
 49  L-WAR    24780 non-null  float64
dtypes: float64(34), int64(12), object(4)
memory usage: 9.5+ MB

In [ ]:
df=df.drop(['IDfg','Season','Name','Team','L-WAR', 'Age Rng'],axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24780 entries, 0 to 24779
Data columns (total 44 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     24780 non-null  int64
 1   G       24780 non-null  int64
 2   AB      24780 non-null  int64
 3   PA      24780 non-null  int64
 4   H       24780 non-null  int64
 5   1B      24780 non-null  int64
 6   2B      24780 non-null  int64
 7   3B      24780 non-null  int64
 8   HR      22873 non-null  float64
 9   R       22925 non-null  float64
 10  RBI     24780 non-null  float64
 11  BB      24780 non-null  int64
 12  IBB     24780 non-null  float64
 13  SO      24780 non-null  float64
 14  HBP     24780 non-null  float64
 15  SF      24780 non-null  float64
 16  SH      24780 non-null  float64
 17  GDP     24780 non-null  float64
 18  SB      24780 non-null  float64
 19  CS      24780 non-null  float64
 20  AVG     24780 non-null  float64
 21  BB%     24780 non-null  float64
 22  K%      24780 non-null  float64
 23  BB/K    24780 non-null  float64
 24  OBP     24780 non-null  float64
 25  SLG     24780 non-null  float64
 26  OPS     24780 non-null  float64
 27  ISO     24780 non-null  float64
 28  BABIP   24780 non-null  float64
 29  wOBA    24780 non-null  float64
 30  wRAA    24780 non-null  float64
 31  wRC     24780 non-null  int64
 32  Bat     24780 non-null  float64
 33  Rep     24780 non-null  float64
 34  Pos     24780 non-null  float64
 35  RAR     24780 non-null  float64
 36  WAR     24780 non-null  float64
 37  Spd     24780 non-null  float64
 38  BsR     24780 non-null  float64
 39  Def     24780 non-null  float64
 40  wSB     24780 non-null  float64
 41  Off     24780 non-null  float64
 42  Lg      24780 non-null  float64
 43  Events  24780 non-null  int64
dtypes: float64(33), int64(11)
memory usage: 8.3 MB

In [ ]:
features = df.columns
print(features)

Index(['Age', 'G', 'AB', 'PA', 'H', '1B', '2B', '3B', 'HR', 'R', 'RBI', 'BB',
       'IBB', 'SO', 'HBP', 'SF', 'SH', 'GDP', 'SB', 'CS', 'AVG', 'BB%', 'K%',
       'BB/K', 'OBP', 'SLG', 'OPS', 'ISO', 'BABIP', 'wOBA', 'wRAA', 'wRC',
       'Bat', 'Rep', 'Pos', 'RAR', 'WAR', 'Spd', 'BsR', 'Def', 'wSB', 'Off',
       'Lg', 'Events'],
      dtype='object')

#EDA2. Single Season WAR Prediction

preparing data to

In [ ]:
x = df[['Age', 'PA', 'G', 'AB', 'H', '1B', '2B', '3B', 'HR', 'R', 'RBI', 'BB', 'IBB', 'SO', 'HBP', 'SF', 'SH','GDP','SB','CS','AVG','BB%','K%','BB/K','OBP','SLG','OPS','ISO','BABIP']]
y = df['WAR']

In [ ]:
# NaN 값을 0으로 대체
x.fillna(0, inplace=True)

# Clip very large or very small values
x = x.clip(lower=-1e10, upper=1e10)

<ipython-input-15-1549f232c389>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x.fillna(0, inplace=True)

In [ ]:
# 표준화
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [ ]:
#훈련세트 테스트세트 나누기
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.2, random_state=42)

In [ ]:
print("훈련 데이터 shape: ", x_train.shape, y_train.shape)
print("테스트 데이터 shape: ", x_test.shape, y_test.shape)

훈련 데이터 shape:  (19824, 29) (19824,)
테스트 데이터 shape:  (4956, 29) (4956,)

SelectKBest 를 이용한 특성 선택

In [ ]:
from sklearn.feature_selection import SelectKBest, mutual_info_regression

# SelectKBest 객체 생성
select_feature = SelectKBest(score_func=mutual_info_regression, k=10)

# SelectKBest 객체를 특성과 타겟과 함께 fit
select_feature.fit(x_train, y_train)

# 선택된 특성의 인덱스 확인
selected_indices = select_feature.get_support(indices=True)

# 실제 특성 이름 가져오기
selected_feature_names = df.columns[selected_indices]

# 점수와 해당하는 특성 이름 표시
print('점수 목록:', select_feature.scores_)
print('특성 목록:', selected_feature_names)

# 특성 선택 수행
featured_x = select_feature.transform(x_train)

점수 목록: [0.04249101 0.83700264 0.53023842 0.80836881 0.80038399 0.70974941
 0.61923642 0.25169534 0.5065679  0.39050044 0.70107153 0.66287841
 0.28504067 0.60715972 0.2825381  0.34379477 0.0650745  0.40140706
 0.28766515 0.25442858 0.67870923 0.43451122 0.47367977 0.44262499
 0.74145785 0.74724633 0.82873491 0.56256725 0.58515282]
특성 목록: Index(['G', 'PA', 'H', '1B', 'RBI', 'BB', 'AVG', 'OBP', 'SLG', 'OPS'], dtype='object')

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error

# 랜덤 포레스트 모델 생성
random_forest_model = RandomForestRegressor(n_estimators=100, random_state=42)

# 특성 선택을 통해 얻은 특성으로 훈련 데이터와 레이블을 사용하여 모델 학습
random_forest_model.fit(featured_x, y_train)

# 테스트 데이터에 대한 특성 선택 수행
x_test_selected = select_feature.transform(x_test)

# 학습된 모델을 사용하여 예측
y_pred = random_forest_model.predict(x_test_selected)

# R-squared 값 계산
r2 = r2_score(y_test, y_pred)
print(f'R-squared: {r2}')

# MAE (Mean Absolute Error) 계산
mae = mean_absolute_error(y_test, y_pred)
print(f'Mean Absolute Error: {mae}')

R-squared: 0.8402582418863507
Mean Absolute Error: 0.44767443370377435